databases:
  - name: social_space
    databaseName: social_space
    user: social_space

services:
  - type: web
    name: social_space
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_space
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false